### ISSUE TITLE
[Balance] Magic crit build is absolutely broken OP 

### ISSUE THREAD

**Issue by MihanDeNoob** [ZsoltMolnarrr/Wizards#61] opened 2024-09-17 21:02 UTC
Maxed out first talalnt tree (lvl42) with crits is absolutely busted, and thats ignoring the ascendant tree. 
Ive been playing arcane mage and dealing insane amount damage, one-two shoting hardest mobs dungeon arise can offer. 
Boss fights (be it data pack mobs or new  bosses from mods or revorked vanilla bosses) were a complete joke since damage was so insane. 

I was dealing around 75 dmg with the arcane crits build (and that ignoring the special ability and beam ability), with almost every spell cast being a crit. I was wearing full arcane robe set and arcane staff (not netherite), with only staff having the enchant (level 3 increased spell dmg) 

All that combing with mods like [RpgDifficulty](https://www.curseforge.com/minecraft/mc-mods/rpgdifficulty) or/and [Dungeon Difficulty [Fabric]](https://www.curseforge.com/minecraft/mc-mods/dungeon-difficulty) and [Majrusz's Progressive Difficulty](https://www.curseforge.com/minecraft/mc-mods/majruszs-progressive-difficulty)

The problem is how high critical damage and crit chances can be boosted in the first tree with big talents. 
So to solve this without nerfing it to the ground or outright reworking the whole thing, only one of these stats need to be nerfed, either reduce the amount crit damage can be boosted or reduce the amount of crit chance boost, that you can get from talents.

**Comment by ZsoltMolnarrr** [comment] 2024-09-17 21:09
Hello,

I understand the frustration.

I suspect you are playing a large modpack, that contains some kind of Talent-tree/Skill-tree mod. 
These mods definitely do influence the balance of RPG Series mods, but you have to see, that these are external factors.
None of these Talent-tree/Skill-tree mods, were made, nor configured by me.

So the problem is not Wizards, but what was built on top if it additionally.
I recommend contacting the modpack authors, to rebalance the trees.

Closing the issue as non-actionable within the scope of Wizards (or Spell Engine) project.

**Closed as completed by ZsoltMolnarrr** 2024-09-17 21:09 UTC

**Comment by ZsoltMolnarrr** [comment] 2024-09-17 21:14
Which modpack were you playing?

**Comment by MihanDeNoob** [comment] 2024-09-18 16:03
Ahh, i see, made a mistake. Ive posted it here when i should have posted it in [Simply Skills](https://modrinth.com/mod/simply-skills) My bad. Ive been building the modpack myself and ive completely forgor that this features comes from the other mod. 
Also, i wasnt frustrated or having bad feels at all,  i def need to rephrase this before posting it on Simply Skills git xdd
